### ISSUE TITLE
Update package name

### ISSUE THREAD

**Issue by randytorres** [dfuse-io/demux-js-dfuse#2]
Hey is it possible to update the package name so it doesn't conflict with the `@dfuse/client` library? Since this doesn't seem to be deployed to npm I'd like to point to this repo in my package.json.

I can open a pr with the change if this works for you

**Comment by olivierbeaulieu** [comment]
Hey @randytorres! Good catch. I just pushed the change to master! It's `demux-dfuse` now. I'll also be deploying the package to npm ASAP.
